### ISSUE TITLE
Chrome Issues

### ISSUE THREAD

**Issue by kyleabeauchamp** [rmcgibbo/slidedeck#31]
I've noticed issues viewing slidedecks in Chrome (Version 40.0.2214.95 (64-bit)
) on both OSX and Ubuntu.  The symptom is a black screen.  The favicon is loaded.  

For example: http://htmlpreview.github.io/?https://github.com/rmcgibbo/slidedeck-example/blob/master/index.html

**Comment by kyleabeauchamp** [comment]
AFAIK, Firefox and Safari still work.

**Comment by kyleabeauchamp** [comment]
Debug js console does this, not sure if that's the problem though:

```
htmlpreview.github.io/:1 Refused to execute script from 'https://raw.githubusercontent.com/rmcgibbo/slidedeck-example/master/js/require-1.0.8.min.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
htmlpreview.github.io/:1 Refused to execute script from 'https://raw.githubusercontent.com/rmcgibbo/slidedeck-example/master/js/slides.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
```

**Comment by kyleabeauchamp** [comment]
Also, I suppose this only happens via htmlpreview

**Comment by rmcgibbo** [comment]
Yeah, `refused to execute script` is definitely the problem.

**Comment by rmcgibbo** [comment]
How about `http://cdn.rawgit.com/rmcgibbo/slidedeck-example/master/index.html`

**Comment by kyleabeauchamp** [comment]
lgtm

On Thu, Feb 5, 2015 at 3:19 PM, Robert T. McGibbon <notifications@github.com

**Comment by rmcgibbo** [comment]
Okay. I'll change links over to that.
