### ISSUE TITLE
'slidedeck' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by Neverwozzer** [rmcgibbo/slidedeck#34]
Hi
I am running Windows 7 64 bit.

I have installed the package (successfully I thought) using pip, easy-install and by downloading the distribution from the Python package repositiory and then using setup.py.

I checked the PATH varialble, and there is a path to ..\Python27\Scripts. Checking the folder, I found a file called slidedeck (no extension) but which appears to be a Python script.

Renaming it to slidedeck.py and attempting to run it just results in Python errors (failure to import render for example).

Any advice to solve the problem would be appreciated.

**Comment by rmcgibbo** [comment]
I think this is a windows bug on our end. Fix coming...

**Comment by rmcgibbo** [comment]
Should be fixed now. Post back if you have any difficulty.

**Comment by Neverwozzer** [comment]
Thanks... getting there. I ran pip install --upgrade slidedeck then tried slidedeck render.
Result:
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\slidedeck.exe\__main__.py", line 9, in <mo
  File "C:\Python27\lib\site-packages\slidedeck\scripts\slidedeck.py",
in main
    render.process_slides(args.markdown, args.output, args.template)
AttributeError: 'ArgumentParser' object has no attribute 'process_slides'
