### ISSUE TITLE
Follow up to #34: AttributeError: 'ArgumentParser' object has no attribute 'process_slides'

### ISSUE THREAD

**Issue by Neverwozzer** [rmcgibbo/slidedeck#36]
Thanks for the quick response. I updated and ran "slidedeck render" with the result below:

Traceback (most recent call last):
File "C:\Python27\lib\runpy.py", line 162, in run_module_as_main
"__main_", fname, loader, pkg_name)
File "C:\Python27\lib\runpy.py", line 72, in run_code
exec code in run_globals
File "C:\Python27\Scripts\slidedeck.exe__main_.py", line 9, in <mo
File "C:\Python27\lib\site-packages\slidedeck\scripts\slidedeck.py",
in main
render.process_slides(args.markdown, args.output, args.template)
AttributeError: 'ArgumentParser' object has no attribute 'process_slides'

**Comment by rmcgibbo** [comment]
looks like i should have tested it before pushing :) will fix soon. its just some silly typos from rearranging modules.

**Comment by rmcgibbo** [comment]
Fixed in efa8ac8ee3ce143c3ff963896ad04a0a12feb598

**Comment by Neverwozzer** [comment]
Thanks for this

it works now.

As a curiosity, it fails on characters like é (letters with accents) on my
Windows machine - I have to replace them with HTML - é = &eacute; while it
is happy on my French colleague's mac.


Closed #36 <https://github.com/rmcgibbo/slidedeck/issues/36>.

**Comment by rmcgibbo** [comment]
What is the error? Is it a traceback that crashes the python process? If
so, can you post it? Also, do you know what encoding your file is saved in?
